name: Django CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    environment: env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set env variables
        run: |
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> $GITHUB_ENV
          echo "DEBUG=${{ secrets.DEBUG }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "LANGUAGE_CODE=${{ secrets.LANGUAGE_CODE }}" >> $GITHUB_ENV
          echo "TIME_ZONE=${{ secrets.TIME_ZONE }}" >> $GITHUB_ENV


      - name: Display environment variables
        run: |
          echo "ALLOWED_HOSTS: $ALLOWED_HOSTS"
          echo "DEBUG: $DEBUG"
          echo "SECRET_KEY: $SECRET_KEY"
          echo "LANGUAGE_CODE: $LANGUAGE_CODE"
          echo "TIME_ZONE: $TIME_ZONE"

      - name: Setup DB
        run: |
          python manage.py migrate --settings=lab2.settings
      
      - name: Run tests
        run: |
          pytest --junitxml=test-results.xml
        continue-on-error: false
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
      
      - name: Archive project
        run: | 
          zip -r project.zip . -x "**/__pycache__/*" "*.pyc" ".git/*" "**.pytest_cache/*" "*.sqlite3"
      
      - name: Upload project archive
        uses: actions/upload-artifact@v4
        with:
          name: project-archive
          path: project.zip
